-- Parts, modifications, and recurring maintenance records for each firearm.

create table if not exists public.parts_modifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  legacy_key text not null,
  firearm_id bigint not null references public.guns(id) on delete cascade,
  title text not null,
  description text,
  date date,
  cost numeric(12,2) check (cost is null or cost >= 0),
  vendor text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, legacy_key)
);

create table if not exists public.maintenance_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  legacy_key text not null,
  firearm_id bigint not null references public.guns(id) on delete cascade,
  date date not null,
  category text not null,
  notes text,
  round_count integer check (round_count is null or round_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, legacy_key)
);

create index if not exists parts_modifications_firearm_date_idx
  on public.parts_modifications (firearm_id, date desc);
create index if not exists maintenance_entries_firearm_date_idx
  on public.maintenance_entries (firearm_id, date desc);

alter table public.parts_modifications enable row level security;
alter table public.maintenance_entries enable row level security;

drop policy if exists "owner select" on public.parts_modifications;
drop policy if exists "owner delete" on public.parts_modifications;
drop policy if exists "owner insert" on public.parts_modifications;
drop policy if exists "owner update" on public.parts_modifications;
create policy "owner select" on public.parts_modifications for select to authenticated using (user_id = auth.uid());
create policy "owner delete" on public.parts_modifications for delete to authenticated using (user_id = auth.uid());
create policy "owner insert" on public.parts_modifications for insert to authenticated
  with check (user_id = auth.uid() and exists (
    select 1 from public.guns g where g.id = firearm_id and g.user_id = auth.uid()
  ));
create policy "owner update" on public.parts_modifications for update to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid() and exists (
    select 1 from public.guns g where g.id = firearm_id and g.user_id = auth.uid()
  ));

drop policy if exists "owner select" on public.maintenance_entries;
drop policy if exists "owner delete" on public.maintenance_entries;
drop policy if exists "owner insert" on public.maintenance_entries;
drop policy if exists "owner update" on public.maintenance_entries;
create policy "owner select" on public.maintenance_entries for select to authenticated using (user_id = auth.uid());
create policy "owner delete" on public.maintenance_entries for delete to authenticated using (user_id = auth.uid());
create policy "owner insert" on public.maintenance_entries for insert to authenticated
  with check (user_id = auth.uid() and exists (
    select 1 from public.guns g where g.id = firearm_id and g.user_id = auth.uid()
  ));
create policy "owner update" on public.maintenance_entries for update to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid() and exists (
    select 1 from public.guns g where g.id = firearm_id and g.user_id = auth.uid()
  ));

grant select, insert, update, delete on public.parts_modifications, public.maintenance_entries to authenticated;
grant usage, select on all sequences in schema public to authenticated;
