-- Sixgun Retriever: private, single-user cloud schema.
-- Run this once in Supabase Dashboard > SQL Editor.

create table if not exists public.guns (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  legacy_key text not null,
  make text,
  model text not null,
  caliber text,
  serial text,
  purchase_date date,
  source text,
  price numeric(12,2),
  rotation_status text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, legacy_key)
);

create table if not exists public.powders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  legacy_key text not null,
  name text not null,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, legacy_key),
  unique (user_id, name)
);

create table if not exists public.loads (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  legacy_key text not null,
  gun_id bigint references public.guns(id) on delete set null,
  powder_id bigint references public.powders(id) on delete set null,
  charge numeric,
  bullet text,
  primer text,
  oal numeric,
  tier integer,
  cartridge text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, legacy_key)
);

create table if not exists public.sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  legacy_key text not null,
  load_id bigint not null references public.loads(id) on delete cascade,
  date date,
  avg_velocity numeric,
  sd numeric,
  es numeric,
  moa numeric,
  notes text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, legacy_key)
);

create table if not exists public.journal_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  legacy_key text not null,
  date date,
  tag text not null check (tag in ('BENCH','RANGE')),
  gun_id bigint references public.guns(id) on delete set null,
  powder_id bigint references public.powders(id) on delete set null,
  note text,
  photo_urls text[] not null default '{}',
  cartridge text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, legacy_key)
);

create table if not exists public.target_analyses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  legacy_key text not null,
  load_id bigint not null references public.loads(id) on delete cascade,
  date date,
  photo_path text,
  scale_box jsonb,
  ref_inches numeric,
  holes jsonb not null default '[]'::jsonb,
  distance_yards numeric,
  group_inches numeric,
  moa numeric,
  mean_radius_inches numeric,
  shots integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, legacy_key)
);

-- Private cloud copies of the app's curated Library content. `data` preserves
-- the single-file UI's exact display model while still making it syncable.
create table if not exists public.library_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  legacy_key text not null,
  cartridge text,
  writer text,
  data jsonb not null,
  updated_at timestamptz not null default now(),
  unique (user_id, legacy_key)
);

create table if not exists public.library_tables (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  legacy_key text not null,
  cartridge text,
  writer text,
  powders text[] not null default '{}',
  data jsonb not null,
  updated_at timestamptz not null default now(),
  unique (user_id, legacy_key)
);

-- Authenticated snapshot for UI-only state: active cartridge, filters,
-- bench prose, inventory compatibility data, and powder favorites.
create table if not exists public.app_state (
  user_id uuid primary key references auth.users(id) on delete cascade,
  state jsonb not null default '{}'::jsonb,
  schema_version integer not null default 1,
  updated_at timestamptz not null default now()
);

do $$
declare t text;
begin
  foreach t in array array[
    'guns','powders','loads','sessions','journal_entries','target_analyses',
    'library_entries','library_tables','app_state'
  ] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "owner select" on public.%I', t);
    execute format('drop policy if exists "owner insert" on public.%I', t);
    execute format('drop policy if exists "owner update" on public.%I', t);
    execute format('drop policy if exists "owner delete" on public.%I', t);
    execute format('create policy "owner select" on public.%I for select to authenticated using (auth.uid() = user_id)', t);
    execute format('create policy "owner insert" on public.%I for insert to authenticated with check (auth.uid() = user_id)', t);
    execute format('create policy "owner update" on public.%I for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id)', t);
    execute format('create policy "owner delete" on public.%I for delete to authenticated using (auth.uid() = user_id)', t);
  end loop;
end $$;

grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('sixgun-photos', 'sixgun-photos', false, 15728640, array['image/jpeg','image/png','image/webp','image/heic','image/heif'])
on conflict (id) do update set public = false;

drop policy if exists "sixgun photo select" on storage.objects;
drop policy if exists "sixgun photo insert" on storage.objects;
drop policy if exists "sixgun photo update" on storage.objects;
drop policy if exists "sixgun photo delete" on storage.objects;

create policy "sixgun photo select" on storage.objects for select to authenticated
using (bucket_id = 'sixgun-photos' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "sixgun photo insert" on storage.objects for insert to authenticated
with check (bucket_id = 'sixgun-photos' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "sixgun photo update" on storage.objects for update to authenticated
using (bucket_id = 'sixgun-photos' and (storage.foldername(name))[1] = auth.uid()::text)
with check (bucket_id = 'sixgun-photos' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "sixgun photo delete" on storage.objects for delete to authenticated
using (bucket_id = 'sixgun-photos' and (storage.foldername(name))[1] = auth.uid()::text);


