-- Gun Biography Letter
-- Run in Supabase Dashboard > SQL Editor before merging the feature.

alter table public.guns
  add column if not exists barrel_length text,
  add column if not exists finish text;

create table if not exists public.app_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  letterhead_name text not null default 'The Sixgun Retriever',
  signature_name text,
  updated_at timestamptz not null default now()
);

create table if not exists public.gun_letters (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  legacy_key text not null,
  gun_id bigint not null references public.guns(id) on delete cascade,
  opening text,
  prompt_answers jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, legacy_key),
  unique (user_id, gun_id)
);

alter table public.app_settings enable row level security;
alter table public.gun_letters enable row level security;

drop policy if exists "owner select" on public.app_settings;
drop policy if exists "owner insert" on public.app_settings;
drop policy if exists "owner update" on public.app_settings;
drop policy if exists "owner delete" on public.app_settings;
create policy "owner select" on public.app_settings for select to authenticated using (auth.uid() = user_id);
create policy "owner insert" on public.app_settings for insert to authenticated with check (auth.uid() = user_id);
create policy "owner update" on public.app_settings for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "owner delete" on public.app_settings for delete to authenticated using (auth.uid() = user_id);

drop policy if exists "owner select" on public.gun_letters;
drop policy if exists "owner insert" on public.gun_letters;
drop policy if exists "owner update" on public.gun_letters;
drop policy if exists "owner delete" on public.gun_letters;
create policy "owner select" on public.gun_letters for select to authenticated using (auth.uid() = user_id);
create policy "owner insert" on public.gun_letters for insert to authenticated with check (auth.uid() = user_id);
create policy "owner update" on public.gun_letters for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "owner delete" on public.gun_letters for delete to authenticated using (auth.uid() = user_id);

grant select, insert, update, delete on public.app_settings, public.gun_letters to authenticated;
grant usage, select on all sequences in schema public to authenticated;
