-- Photographic Record: ordered firearm moments with private image renditions.
-- Run after 20260826_gun_biography_letter.sql.

create table if not exists public.gun_photo_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  gun_id bigint not null references public.guns(id) on delete cascade,
  title text not null default 'Photographic Record',
  subtitle text not null default 'Selected moments from the life of this sixgun',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, gun_id)
);

create table if not exists public.gun_photo_moments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  legacy_key text not null,
  gun_id bigint not null references public.guns(id) on delete cascade,
  title text not null,
  subtitle text,
  moment_date date,
  season_year text,
  location text,
  caption text,
  sort_position integer not null default 0,
  is_featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, legacy_key)
);

create table if not exists public.gun_moment_photos (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  legacy_key text not null,
  moment_id bigint not null references public.gun_photo_moments(id) on delete cascade,
  display_path text not null,
  print_path text not null,
  original_filename text,
  mime_type text,
  pixel_width integer,
  pixel_height integer,
  sort_position integer not null default 0,
  is_featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, legacy_key)
);

create index if not exists gun_photo_moments_gun_order_idx
  on public.gun_photo_moments (gun_id, sort_position);
create index if not exists gun_moment_photos_moment_order_idx
  on public.gun_moment_photos (moment_id, sort_position);

alter table public.gun_photo_records enable row level security;
alter table public.gun_photo_moments enable row level security;
alter table public.gun_moment_photos enable row level security;

do $$
declare t text;
begin
  foreach t in array array['gun_photo_records','gun_photo_moments','gun_moment_photos'] loop
    execute format('drop policy if exists "owner select" on public.%I', t);
    execute format('drop policy if exists "owner insert" on public.%I', t);
    execute format('drop policy if exists "owner update" on public.%I', t);
    execute format('drop policy if exists "owner delete" on public.%I', t);
    execute format('create policy "owner select" on public.%I for select to authenticated using (auth.uid() = user_id)', t);
    execute format('create policy "owner insert" on public.%I for insert to authenticated with check (auth.uid() = user_id)', t);
    execute format('create policy "owner update" on public.%I for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id)', t);
    execute format('create policy "owner delete" on public.%I for delete to authenticated using (auth.uid() = user_id)', t);
  end loop;
end $$;

-- Relationship checks prevent a user-owned row from being attached to a gun
-- or Moment belonging to a different account, even if an ID were guessed.
drop policy if exists "owner insert" on public.gun_photo_records;
drop policy if exists "owner update" on public.gun_photo_records;
create policy "owner insert" on public.gun_photo_records for insert to authenticated
with check (auth.uid() = user_id and exists (
  select 1 from public.guns g where g.id = gun_id and g.user_id = auth.uid()
));
create policy "owner update" on public.gun_photo_records for update to authenticated
using (auth.uid() = user_id) with check (auth.uid() = user_id and exists (
  select 1 from public.guns g where g.id = gun_id and g.user_id = auth.uid()
));

drop policy if exists "owner insert" on public.gun_photo_moments;
drop policy if exists "owner update" on public.gun_photo_moments;
create policy "owner insert" on public.gun_photo_moments for insert to authenticated
with check (auth.uid() = user_id and exists (
  select 1 from public.guns g where g.id = gun_id and g.user_id = auth.uid()
));
create policy "owner update" on public.gun_photo_moments for update to authenticated
using (auth.uid() = user_id) with check (auth.uid() = user_id and exists (
  select 1 from public.guns g where g.id = gun_id and g.user_id = auth.uid()
));

drop policy if exists "owner insert" on public.gun_moment_photos;
drop policy if exists "owner update" on public.gun_moment_photos;
create policy "owner insert" on public.gun_moment_photos for insert to authenticated
with check (auth.uid() = user_id and exists (
  select 1 from public.gun_photo_moments m where m.id = moment_id and m.user_id = auth.uid()
));
create policy "owner update" on public.gun_moment_photos for update to authenticated
using (auth.uid() = user_id) with check (auth.uid() = user_id and exists (
  select 1 from public.gun_photo_moments m where m.id = moment_id and m.user_id = auth.uid()
));

grant select, insert, update, delete on
  public.gun_photo_records, public.gun_photo_moments, public.gun_moment_photos
  to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- Print renditions may be larger than existing journal/target images.
update storage.buckets
set file_size_limit = 20971520,
    allowed_mime_types = array['image/jpeg','image/png','image/webp','image/heic','image/heif']
where id = 'sixgun-photos';
