-- Additive bullet catalog migration. Existing load.bullet text remains the
-- backward-compatible display value; bullet_id adds stable identity.
create table if not exists public.bullets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  legacy_key text not null,
  manufacturer text,
  product text not null,
  weight_gr numeric,
  diameter text,
  caliber text,
  style text,
  notes text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, legacy_key)
);

alter table public.loads add column if not exists bullet_id bigint references public.bullets(id) on delete set null;
create index if not exists loads_bullet_id_idx on public.loads(bullet_id);
alter table public.bullets enable row level security;
drop policy if exists "owner select" on public.bullets;
drop policy if exists "owner insert" on public.bullets;
drop policy if exists "owner update" on public.bullets;
drop policy if exists "owner delete" on public.bullets;
create policy "owner select" on public.bullets for select to authenticated using (auth.uid() = user_id);
create policy "owner insert" on public.bullets for insert to authenticated with check (auth.uid() = user_id);
create policy "owner update" on public.bullets for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "owner delete" on public.bullets for delete to authenticated using (auth.uid() = user_id);
grant select, insert, update, delete on public.bullets to authenticated;
grant usage, select on all sequences in schema public to authenticated;
