-- Garmin ShotView session imports and per-shot chronograph data.
-- Run after 20260826_parts_maintenance.sql.

alter table public.sessions
  add column if not exists firearm_id bigint references public.guns(id) on delete set null,
  add column if not exists session_datetime timestamptz,
  add column if not exists shot_count integer,
  add column if not exists source text,
  add column if not exists source_filename text,
  add column if not exists garmin_avg_velocity numeric,
  add column if not exists garmin_sd numeric,
  add column if not exists garmin_es numeric;

create table if not exists public.chronograph_shots (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  session_id bigint not null references public.sessions(id) on delete cascade,
  shot_number integer not null,
  speed numeric not null,
  shot_time text,
  clean_bore boolean,
  cold_bore boolean,
  shot_notes text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, session_id, shot_number)
);

create index if not exists chronograph_shots_session_id_idx
  on public.chronograph_shots (session_id, shot_number);

create index if not exists sessions_firearm_id_idx
  on public.sessions (firearm_id);

alter table public.chronograph_shots enable row level security;

drop policy if exists "owner select" on public.chronograph_shots;
drop policy if exists "owner insert" on public.chronograph_shots;
drop policy if exists "owner update" on public.chronograph_shots;
drop policy if exists "owner delete" on public.chronograph_shots;

create policy "owner select" on public.chronograph_shots
  for select to authenticated using (auth.uid() = user_id);
create policy "owner insert" on public.chronograph_shots
  for insert to authenticated with check (auth.uid() = user_id);
create policy "owner update" on public.chronograph_shots
  for update to authenticated using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
create policy "owner delete" on public.chronograph_shots
  for delete to authenticated using (auth.uid() = user_id);

grant select, insert, update, delete on public.chronograph_shots to authenticated;
grant usage, select on sequence public.chronograph_shots_id_seq to authenticated;
