-- Phase 1: Gun Biography

alter table public.guns
  add column if not exists rotation_note text;

create table if not exists public.gun_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  legacy_key text not null,
  gun_id bigint not null references public.guns(id) on delete cascade,
  date date,
  text text not null,
  photo_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, legacy_key)
);

alter table public.gun_entries enable row level security;

drop policy if exists "owner select" on public.gun_entries;
drop policy if exists "owner insert" on public.gun_entries;
drop policy if exists "owner update" on public.gun_entries;
drop policy if exists "owner delete" on public.gun_entries;

create policy "owner select" on public.gun_entries
for select to authenticated using (auth.uid() = user_id);
create policy "owner insert" on public.gun_entries
for insert to authenticated with check (auth.uid() = user_id);
create policy "owner update" on public.gun_entries
for update to authenticated using (auth.uid() = user_id)
with check (auth.uid() = user_id);
create policy "owner delete" on public.gun_entries
for delete to authenticated using (auth.uid() = user_id);

grant select, insert, update, delete on public.gun_entries to authenticated;
grant usage, select on all sequences in schema public to authenticated;
